import { v4 as uuid } from 'uuid';
import { Stock } from './types';
import { UUID } from 'crypto';

export function buildStock(data: any): Stock {
  return {
    id: uuid() as UUID, // this would normally be generated by the db as a pk
    currentPrice: data.regularMarketPrice,
    symbol: data.symbol.toUpperCase(),
    displayName: data.displayName,
  };
}
